version: "3"

services:
  django:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - DJANGO_CONFIGURATION=Local
    build:
      context: ../../
      dockerfile: docker/images/local/Django.Dockerfile
    container_name: django
    volumes:
      - ../../:/code
    ports:
      - "8000:8000"
    command:
      - /start
